app:
  frontend:
    url: http://localhost:5173

server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: login_service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: crm_service
          uri: http://localhost:8082
          predicates:
            - Path=/testAPI/**
          filters:
            - StripPrefix=1

jwt:
  secret: umaChaveSuperSecreta123456789012345678901234
  logging:
    debug-enabled: false
    log-user-info: false
