name: CI

on:
  push:
    paths:
      - 'login_service/**'
  pull_request:
    paths:
      - 'login_service/**'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17

      - name: Run Unit Tests
        working-directory: ./login_service
        run: mvn clean test -Punit

  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17

      - name: Run Integration Tests
        working-directory: ./login_service
        run: mvn verify -Pintegration
